### ISSUE TITLE
Conversion function for moving between nlme-style and lme4ord-style reStructs

### ISSUE THREAD

**Issue by stevencarlislewalker** [stevencarlislewalker/lme4ord#16]
The challenge is that `nlme` parameterizes on the _inverse_ Cholesky factor as opposed to the Cholesky factor of the covariance/correlation matrices.  So it seems wasteful to not just write special methods for `lme4ord`.  On the other hand, it might be worth it just to provide methods that will match expectations of those used to `nlme`.

**Comment by bbolker** [comment]
I guess the point is that it is indeed computationally wasteful (although the cost of inverting a Cholesky factor (using `backsolve()`?) must be many times smaller than the cost of computing one from scratch, at least in those cases where a closed-form expression is not available.   The purpose (in my mind) of doing this is so that users automatically have access to any `corStruct`s that have been previously written.  It makes plenty of sense to re-code the commonly used ones for efficiency, thought ...

(Indeed, `src/corStruct.c` in `nlme` contains this generic code for getting the inverse-Cholesky for a geostatistical correlation structure, called from `nlme:::corMatrix.corSpatial`.)

```
   spatial_mat(par, dist, n, nug, corr, mat);    /* get spatial correlation matrix */
    F77_CALL(chol) (mat, n, n, mat, &info);  /* cholesky */
    for(i = 0; i < *n; i++) {
        work1[i * np1] = 1;
        F77_CALL(dtrsl) (mat, n, n, work1 + i * (*n), &job, &info);  /* backsolve */
        *logdet -= log(fabs(mat[i * np1]));
    }
```

**Comment by stevencarlislewalker** [comment]
Makes sense.  I've already started coding it up, and it actually isn't so painful.

**Comment by stevencarlislewalker** [comment]
first attempt:  6d1ca3df05

**Comment by stevencarlislewalker** [comment]
closing for now.  documentation is the main thing to do though.
